---
- name: basics
  hosts: all
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: install software
      become: yes
      become_method: sudo
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - make
          - git
          - htop
          - jq
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
          - go-dep
- name: install go
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - include_role:
      name: ansible-go
    vars:
      go_tarball: "go1.11.linux-amd64.tar.gz"
      go_tarball_checksum: "sha256:b3fcf280ff86558e0559e185b601c9eade0fd24c900b4c63cd14d1d38613e499"
      go_version_target: "go version go1.11 linux/amd64"
      set_go_path: true
- name: install pilosa-ingester
  hosts: all
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: pull pilosa-ingester
      git:
        dest: /home/ubuntu/go/src/github.com/dmibor/pilosa-ingester
        repo: "{{ repo }}"
        version: "{{ version }}"
        force: true
      vars:
        repo: https://github.com/jaffee/pilosa-ingester
        version: master
    - name: install pilosa-ingester
      command: bash -c 'source /etc/profile.d/go-bin.sh; source /etc/profile.d/go-path.sh; dep ensure && go install ./...'
      args:
        chdir: /home/ubuntu/go/src/github.com/dmibor/pilosa-ingester
